# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from grpcsupport.protobuf import game_data_pb2 as grpcsupport_dot_protobuf_dot_game__data__pb2


class BotStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetControllerState = channel.unary_unary(
        '/rlbot.api.Bot/GetControllerState',
        request_serializer=grpcsupport_dot_protobuf_dot_game__data__pb2.GameTickPacket.SerializeToString,
        response_deserializer=grpcsupport_dot_protobuf_dot_game__data__pb2.ControllerState.FromString,
        )


class BotServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetControllerState(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BotServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetControllerState': grpc.unary_unary_rpc_method_handler(
          servicer.GetControllerState,
          request_deserializer=grpcsupport_dot_protobuf_dot_game__data__pb2.GameTickPacket.FromString,
          response_serializer=grpcsupport_dot_protobuf_dot_game__data__pb2.ControllerState.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'rlbot.api.Bot', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
