# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'agent_customisation_3.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AgentPresetCustomiser(object):
    def setupUi(self, AgentPresetCustomiser):
        AgentPresetCustomiser.setObjectName("AgentPresetCustomiser")
        AgentPresetCustomiser.resize(544, 447)
        self.horizontalLayout = QtWidgets.QHBoxLayout(AgentPresetCustomiser)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(AgentPresetCustomiser)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.presets_listwidget = QtWidgets.QListWidget(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.presets_listwidget.sizePolicy().hasHeightForWidth())
        self.presets_listwidget.setSizePolicy(sizePolicy)
        self.presets_listwidget.setMinimumSize(QtCore.QSize(150, 0))
        self.presets_listwidget.setObjectName("presets_listwidget")
        self.verticalLayout.addWidget(self.presets_listwidget)
        self.frame = QtWidgets.QFrame(self.groupBox_3)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.right_frame = QtWidgets.QFrame(AgentPresetCustomiser)
        self.right_frame.setObjectName("right_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.right_frame)
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.right_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 6, 0, 1, 1)
        self.preset_path_lineedit = QtWidgets.QLineEdit(self.groupBox_2)
        self.preset_path_lineedit.setObjectName("preset_path_lineedit")
        self.gridLayout_2.addWidget(self.preset_path_lineedit, 3, 1, 1, 3)
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 3, 0, 1, 1)
        self.preset_new_pushbutton = QtWidgets.QPushButton(self.groupBox_2)
        self.preset_new_pushbutton.setObjectName("preset_new_pushbutton")
        self.gridLayout_2.addWidget(self.preset_new_pushbutton, 7, 0, 1, 1)
        self.preset_load_pushbutton = QtWidgets.QPushButton(self.groupBox_2)
        self.preset_load_pushbutton.setObjectName("preset_load_pushbutton")
        self.gridLayout_2.addWidget(self.preset_load_pushbutton, 7, 1, 1, 1)
        self.preset_autosave_checkbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.preset_autosave_checkbox.setChecked(True)
        self.preset_autosave_checkbox.setObjectName("preset_autosave_checkbox")
        self.gridLayout_2.addWidget(self.preset_autosave_checkbox, 7, 3, 1, 1)
        self.preset_save_pushbutton = QtWidgets.QPushButton(self.groupBox_2)
        self.preset_save_pushbutton.setObjectName("preset_save_pushbutton")
        self.gridLayout_2.addWidget(self.preset_save_pushbutton, 7, 2, 1, 1)
        self.preset_python_file_lineedit = QtWidgets.QLineEdit(self.groupBox_2)
        self.preset_python_file_lineedit.setObjectName("preset_python_file_lineedit")
        self.gridLayout_2.addWidget(self.preset_python_file_lineedit, 6, 1, 1, 3)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.agent_parameters_groupbox = QtWidgets.QGroupBox(self.right_frame)
        self.agent_parameters_groupbox.setObjectName("agent_parameters_groupbox")
        self.verticalLayout_4.addWidget(self.agent_parameters_groupbox)
        self.verticalLayout_4.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.right_frame)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)

        self.retranslateUi(AgentPresetCustomiser)
        QtCore.QMetaObject.connectSlotsByName(AgentPresetCustomiser)

    def retranslateUi(self, AgentPresetCustomiser):
        _translate = QtCore.QCoreApplication.translate
        AgentPresetCustomiser.setWindowTitle(_translate("AgentPresetCustomiser", "Agent Preset Customiser"))
        self.groupBox_3.setTitle(_translate("AgentPresetCustomiser", "Agent Presets"))
        self.groupBox_2.setTitle(_translate("AgentPresetCustomiser", "Preset Config"))
        self.label.setText(_translate("AgentPresetCustomiser", "Python File:"))
        self.label_17.setText(_translate("AgentPresetCustomiser", "File Path:"))
        self.preset_new_pushbutton.setText(_translate("AgentPresetCustomiser", "New"))
        self.preset_load_pushbutton.setText(_translate("AgentPresetCustomiser", "Load"))
        self.preset_autosave_checkbox.setText(_translate("AgentPresetCustomiser", "Autosave"))
        self.preset_save_pushbutton.setText(_translate("AgentPresetCustomiser", "Save"))
        self.agent_parameters_groupbox.setTitle(_translate("AgentPresetCustomiser", "Agent Parameters"))

