# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Harry\Documents\Rocket League\bot\v4\RLBotFramework\gui\qt_gui\car_customisation_3.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(792, 450)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.presets_listwidget = QtWidgets.QListWidget(self.groupBox_3)
        self.presets_listwidget.setObjectName("presets_listwidget")
        self.horizontalLayout_2.addWidget(self.presets_listwidget)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.spinBox_18 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_18.setObjectName("spinBox_18")
        self.gridLayout.addWidget(self.spinBox_18, 2, 5, 1, 2)
        self.comboBox_18 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_18.setObjectName("comboBox_18")
        self.gridLayout.addWidget(self.comboBox_18, 6, 6, 1, 1)
        self.comboBox_8 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_8.setObjectName("comboBox_8")
        self.gridLayout.addWidget(self.comboBox_8, 10, 3, 1, 1)
        self.comboBox_20 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_20.setObjectName("comboBox_20")
        self.gridLayout.addWidget(self.comboBox_20, 10, 6, 1, 1)
        self.comboBox_21 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_21.setObjectName("comboBox_21")
        self.gridLayout.addWidget(self.comboBox_21, 8, 6, 1, 1)
        self.comboBox_15 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_15.setObjectName("comboBox_15")
        self.gridLayout.addWidget(self.comboBox_15, 13, 6, 1, 1)
        self.comboBox_12 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_12.setObjectName("comboBox_12")
        self.gridLayout.addWidget(self.comboBox_12, 4, 6, 1, 1)
        self.spinBox_24 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_24.setObjectName("spinBox_24")
        self.gridLayout.addWidget(self.spinBox_24, 1, 5, 1, 2)
        self.comboBox_22 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_22.setObjectName("comboBox_22")
        self.gridLayout.addWidget(self.comboBox_22, 5, 6, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout.addWidget(self.comboBox_2, 4, 3, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_6.setObjectName("comboBox_6")
        self.gridLayout.addWidget(self.comboBox_6, 8, 3, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout.addWidget(self.comboBox_3, 5, 3, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout.addWidget(self.comboBox_4, 6, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.comboBox_13 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_13.setObjectName("comboBox_13")
        self.gridLayout.addWidget(self.comboBox_13, 3, 6, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout.addWidget(self.spinBox_3, 3, 2, 1, 1)
        self.spinBox_19 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_19.setObjectName("spinBox_19")
        self.gridLayout.addWidget(self.spinBox_19, 3, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.spinBox_23 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_23.setObjectName("spinBox_23")
        self.gridLayout.addWidget(self.spinBox_23, 4, 5, 1, 1)
        self.spinBox_4 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout.addWidget(self.spinBox_4, 4, 2, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 3, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.spinBox_16 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_16.setObjectName("spinBox_16")
        self.gridLayout.addWidget(self.spinBox_16, 6, 5, 1, 1)
        self.comboBox_14 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_14.setObjectName("comboBox_14")
        self.gridLayout.addWidget(self.comboBox_14, 7, 6, 1, 1)
        self.spinBox_6 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_6.setObjectName("spinBox_6")
        self.gridLayout.addWidget(self.spinBox_6, 6, 2, 1, 1)
        self.spinBox_7 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_7.setObjectName("spinBox_7")
        self.gridLayout.addWidget(self.spinBox_7, 7, 2, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_5.setObjectName("comboBox_5")
        self.gridLayout.addWidget(self.comboBox_5, 7, 3, 1, 1)
        self.spinBox_17 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_17.setObjectName("spinBox_17")
        self.gridLayout.addWidget(self.spinBox_17, 5, 5, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.spinBox_14 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_14.setObjectName("spinBox_14")
        self.gridLayout.addWidget(self.spinBox_14, 7, 5, 1, 1)
        self.spinBox_5 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_5.setObjectName("spinBox_5")
        self.gridLayout.addWidget(self.spinBox_5, 5, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 8, 0, 1, 1)
        self.spinBox_22 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_22.setObjectName("spinBox_22")
        self.gridLayout.addWidget(self.spinBox_22, 8, 5, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 9, 0, 1, 1)
        self.spinBox_9 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_9.setObjectName("spinBox_9")
        self.gridLayout.addWidget(self.spinBox_9, 9, 2, 1, 1)
        self.spinBox_26 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_26.setObjectName("spinBox_26")
        self.gridLayout.addWidget(self.spinBox_26, 9, 5, 1, 1)
        self.comboBox_7 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_7.setObjectName("comboBox_7")
        self.gridLayout.addWidget(self.comboBox_7, 9, 3, 1, 1)
        self.spinBox_8 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_8.setObjectName("spinBox_8")
        self.gridLayout.addWidget(self.spinBox_8, 8, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 10, 0, 1, 1)
        self.spinBox_10 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_10.setObjectName("spinBox_10")
        self.gridLayout.addWidget(self.spinBox_10, 10, 2, 1, 1)
        self.spinBox_25 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_25.setObjectName("spinBox_25")
        self.gridLayout.addWidget(self.spinBox_25, 10, 5, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 11, 0, 1, 1)
        self.spinBox_11 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_11.setObjectName("spinBox_11")
        self.gridLayout.addWidget(self.spinBox_11, 11, 2, 1, 1)
        self.spinBox_21 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_21.setObjectName("spinBox_21")
        self.gridLayout.addWidget(self.spinBox_21, 11, 5, 1, 1)
        self.comboBox_10 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_10.setObjectName("comboBox_10")
        self.gridLayout.addWidget(self.comboBox_10, 12, 3, 1, 1)
        self.spinBox_12 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_12.setObjectName("spinBox_12")
        self.gridLayout.addWidget(self.spinBox_12, 12, 2, 1, 1)
        self.spinBox_15 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_15.setObjectName("spinBox_15")
        self.gridLayout.addWidget(self.spinBox_15, 12, 5, 1, 1)
        self.comboBox_19 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_19.setObjectName("comboBox_19")
        self.gridLayout.addWidget(self.comboBox_19, 11, 6, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 12, 0, 1, 1)
        self.comboBox_16 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_16.setObjectName("comboBox_16")
        self.gridLayout.addWidget(self.comboBox_16, 12, 6, 1, 1)
        self.comboBox_9 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_9.setObjectName("comboBox_9")
        self.gridLayout.addWidget(self.comboBox_9, 11, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 13, 0, 1, 1)
        self.comboBox_17 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_17.setObjectName("comboBox_17")
        self.gridLayout.addWidget(self.comboBox_17, 9, 6, 1, 1)
        self.comboBox_11 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_11.setObjectName("comboBox_11")
        self.gridLayout.addWidget(self.comboBox_11, 13, 3, 1, 1)
        self.spinBox_13 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_13.setObjectName("spinBox_13")
        self.gridLayout.addWidget(self.spinBox_13, 13, 2, 1, 1)
        self.spinBox_20 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_20.setObjectName("spinBox_20")
        self.gridLayout.addWidget(self.spinBox_20, 13, 5, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 0, 5, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 2, 1, 2)
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 0, 1, 14, 1)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 4, 14, 1)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 1, 2, 1, 2)
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout.addWidget(self.spinBox_2, 2, 2, 1, 2)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setColumnStretch(3, 2)
        self.gridLayout.setColumnStretch(4, 1)
        self.gridLayout.setColumnStretch(5, 1)
        self.gridLayout.setColumnStretch(6, 2)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.groupBox_2)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 1, 1, 3)
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 1, 0, 1, 2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 1, 2, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.frame)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_2.addWidget(self.toolButton, 1, 3, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.line_3 = QtWidgets.QFrame(self.groupBox_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.frame_2 = QtWidgets.QFrame(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        self.horizontalLayout.setStretch(2, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Preset Loadout Customiser"))
        self.groupBox_3.setTitle(_translate("Form", "Presets"))
        self.groupBox.setTitle(_translate("Form", "Preset Loadout"))
        self.label.setText(_translate("Form", "Primary color:"))
        self.label_2.setText(_translate("Form", "Secondary color:"))
        self.label_5.setText(_translate("Form", "Wheels:"))
        self.label_3.setText(_translate("Form", "Car:"))
        self.label_4.setText(_translate("Form", "Decal:"))
        self.label_6.setText(_translate("Form", "Boost:"))
        self.label_7.setText(_translate("Form", "Antenna:"))
        self.label_8.setText(_translate("Form", "Hat:"))
        self.label_9.setText(_translate("Form", "Paint finish:"))
        self.label_10.setText(_translate("Form", "Custom finish:"))
        self.label_11.setText(_translate("Form", "Engine audio:"))
        self.label_12.setText(_translate("Form", "Trails:"))
        self.label_13.setText(_translate("Form", "Goal explosion:"))
        self.label_15.setText(_translate("Form", "Orange"))
        self.label_14.setText(_translate("Form", "Blue"))
        self.groupBox_2.setTitle(_translate("Form", "Preset Config"))
        self.label_16.setText(_translate("Form", "Name:"))
        self.label_17.setText(_translate("Form", "idk what else:"))
        self.toolButton.setText(_translate("Form", "..."))
        self.pushButton.setText(_translate("Form", "Save Preset"))

