# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(629, 342)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(150, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.blue_listwidget = QtWidgets.QListWidget(self.groupBox)
        self.blue_listwidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.blue_listwidget.setObjectName("blue_listwidget")
        self.verticalLayout.addWidget(self.blue_listwidget)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(150, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.orange_listwidget = QtWidgets.QListWidget(self.groupBox_2)
        self.orange_listwidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.orange_listwidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.orange_listwidget.setObjectName("orange_listwidget")
        self.verticalLayout_2.addWidget(self.orange_listwidget)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.bot_combobox = QtWidgets.QComboBox(self.frame)
        self.bot_combobox.setObjectName("bot_combobox")
        self.horizontalLayout_2.addWidget(self.bot_combobox)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 3)
        self.verticalLayout_3.addWidget(self.frame)
        self.line = QtWidgets.QFrame(self.groupBox_3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.team_frame = QtWidgets.QFrame(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.team_frame.sizePolicy().hasHeightForWidth())
        self.team_frame.setSizePolicy(sizePolicy)
        self.team_frame.setMinimumSize(QtCore.QSize(0, 20))
        self.team_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.team_frame.setObjectName("team_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.team_frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.blue_radiobutton = QtWidgets.QRadioButton(self.team_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blue_radiobutton.sizePolicy().hasHeightForWidth())
        self.blue_radiobutton.setSizePolicy(sizePolicy)
        self.blue_radiobutton.setMinimumSize(QtCore.QSize(50, 0))
        self.blue_radiobutton.setObjectName("blue_radiobutton")
        self.horizontalLayout_4.addWidget(self.blue_radiobutton)
        self.orange_radiobutton = QtWidgets.QRadioButton(self.team_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orange_radiobutton.sizePolicy().hasHeightForWidth())
        self.orange_radiobutton.setSizePolicy(sizePolicy)
        self.orange_radiobutton.setObjectName("orange_radiobutton")
        self.horizontalLayout_4.addWidget(self.orange_radiobutton)
        self.verticalLayout_3.addWidget(self.team_frame)
        self.line_4 = QtWidgets.QFrame(self.groupBox_3)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_3.addWidget(self.line_4)
        self.frame_2 = QtWidgets.QFrame(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.loadout_preset_combobox = QtWidgets.QComboBox(self.frame_2)
        self.loadout_preset_combobox.setObjectName("loadout_preset_combobox")
        self.gridLayout.addWidget(self.loadout_preset_combobox, 1, 1, 1, 1)
        self.loadout_preset_toolbutton = QtWidgets.QToolButton(self.frame_2)
        self.loadout_preset_toolbutton.setObjectName("loadout_preset_toolbutton")
        self.gridLayout.addWidget(self.loadout_preset_toolbutton, 1, 2, 1, 1)
        self.ign_lineedit = QtWidgets.QLineEdit(self.frame_2)
        self.ign_lineedit.setObjectName("ign_lineedit")
        self.gridLayout.addWidget(self.ign_lineedit, 0, 1, 1, 2)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 2)
        self.gridLayout.setColumnStretch(2, 1)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.line_2 = QtWidgets.QFrame(self.groupBox_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.psyonix_bot_frame = QtWidgets.QFrame(self.groupBox_3)
        self.psyonix_bot_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.psyonix_bot_frame.setObjectName("psyonix_bot_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.psyonix_bot_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.psyonix_bot_frame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.bot_level_slider = QtWidgets.QSlider(self.psyonix_bot_frame)
        self.bot_level_slider.setMaximum(100)
        self.bot_level_slider.setProperty("value", 100)
        self.bot_level_slider.setOrientation(QtCore.Qt.Horizontal)
        self.bot_level_slider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.bot_level_slider.setTickInterval(50)
        self.bot_level_slider.setObjectName("bot_level_slider")
        self.horizontalLayout_3.addWidget(self.bot_level_slider)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 5)
        self.verticalLayout_3.addWidget(self.psyonix_bot_frame)
        self.agent_bot_frame = QtWidgets.QFrame(self.groupBox_3)
        self.agent_bot_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.agent_bot_frame.setObjectName("agent_bot_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.agent_bot_frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.agent_bot_frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.agent_lineedit = QtWidgets.QLineEdit(self.agent_bot_frame)
        self.agent_lineedit.setObjectName("agent_lineedit")
        self.gridLayout_2.addWidget(self.agent_lineedit, 0, 1, 1, 1)
        self.agent_toolbutton = QtWidgets.QToolButton(self.agent_bot_frame)
        self.agent_toolbutton.setObjectName("agent_toolbutton")
        self.gridLayout_2.addWidget(self.agent_toolbutton, 0, 2, 1, 1)
        self.agent_flip_turning_checkbox = QtWidgets.QCheckBox(self.agent_bot_frame)
        self.agent_flip_turning_checkbox.setObjectName("agent_flip_turning_checkbox")
        self.gridLayout_2.addWidget(self.agent_flip_turning_checkbox, 1, 0, 1, 3)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 2)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.verticalLayout_3.addWidget(self.agent_bot_frame)
        self.line_3 = QtWidgets.QFrame(self.groupBox_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.button_frame = QtWidgets.QFrame(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_frame.sizePolicy().hasHeightForWidth())
        self.button_frame.setSizePolicy(sizePolicy)
        self.button_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.button_frame.setObjectName("button_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.button_frame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.add_bot_pushbutton = QtWidgets.QPushButton(self.button_frame)
        self.add_bot_pushbutton.setObjectName("add_bot_pushbutton")
        self.horizontalLayout_5.addWidget(self.add_bot_pushbutton)
        self.verticalLayout_3.addWidget(self.button_frame)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 629, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RLBot"))
        self.groupBox.setTitle(_translate("MainWindow", "Blue"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Orange"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Bot Config"))
        self.label.setText(_translate("MainWindow", "Bot:"))
        self.bot_combobox.setToolTip(_translate("MainWindow", "Select bot"))
        self.blue_radiobutton.setText(_translate("MainWindow", "Blue"))
        self.orange_radiobutton.setText(_translate("MainWindow", "Orange"))
        self.label_3.setText(_translate("MainWindow", "IGN:"))
        self.label_4.setText(_translate("MainWindow", "Loadout Preset:"))
        self.loadout_preset_toolbutton.setText(_translate("MainWindow", "..."))
        self.label_2.setText(_translate("MainWindow", "Bot Level:"))
        self.label_5.setText(_translate("MainWindow", "Agent:"))
        self.agent_toolbutton.setText(_translate("MainWindow", "..."))
        self.agent_flip_turning_checkbox.setText(_translate("MainWindow", "flip_turning"))
        self.add_bot_pushbutton.setText(_translate("MainWindow", "Add bot"))

