// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: game_data.proto
// </auto-generated>
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Rlbot.Api {
  public static partial class Bot
  {
    static readonly string __ServiceName = "rlbot.api.Bot";

    static readonly grpc::Marshaller<global::Rlbot.Api.GameTickPacket> __Marshaller_GameTickPacket = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Rlbot.Api.GameTickPacket.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Rlbot.Api.ControllerState> __Marshaller_ControllerState = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Rlbot.Api.ControllerState.Parser.ParseFrom);

    static readonly grpc::Method<global::Rlbot.Api.GameTickPacket, global::Rlbot.Api.ControllerState> __Method_GetControllerState = new grpc::Method<global::Rlbot.Api.GameTickPacket, global::Rlbot.Api.ControllerState>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetControllerState",
        __Marshaller_GameTickPacket,
        __Marshaller_ControllerState);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Rlbot.Api.GameDataReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Bot</summary>
    public abstract partial class BotBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Rlbot.Api.ControllerState> GetControllerState(global::Rlbot.Api.GameTickPacket request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Bot</summary>
    public partial class BotClient : grpc::ClientBase<BotClient>
    {
      /// <summary>Creates a new client for Bot</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public BotClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Bot that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public BotClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected BotClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected BotClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Rlbot.Api.ControllerState GetControllerState(global::Rlbot.Api.GameTickPacket request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetControllerState(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Rlbot.Api.ControllerState GetControllerState(global::Rlbot.Api.GameTickPacket request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetControllerState, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Rlbot.Api.ControllerState> GetControllerStateAsync(global::Rlbot.Api.GameTickPacket request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetControllerStateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Rlbot.Api.ControllerState> GetControllerStateAsync(global::Rlbot.Api.GameTickPacket request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetControllerState, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override BotClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new BotClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(BotBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetControllerState, serviceImpl.GetControllerState).Build();
    }

  }
}
#endregion
