// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace rlbot.flat
{

using global::System;
using global::FlatBuffers;

public struct BallInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static BallInfo GetRootAsBallInfo(ByteBuffer _bb) { return GetRootAsBallInfo(_bb, new BallInfo()); }
  public static BallInfo GetRootAsBallInfo(ByteBuffer _bb, BallInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public BallInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Physics? Physics { get { int o = __p.__offset(4); return o != 0 ? (Physics?)(new Physics()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public Touch? LatestTouch { get { int o = __p.__offset(6); return o != 0 ? (Touch?)(new Touch()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<BallInfo> CreateBallInfo(FlatBufferBuilder builder,
      Offset<Physics> physicsOffset = default(Offset<Physics>),
      Offset<Touch> latestTouchOffset = default(Offset<Touch>)) {
    builder.StartObject(2);
    BallInfo.AddLatestTouch(builder, latestTouchOffset);
    BallInfo.AddPhysics(builder, physicsOffset);
    return BallInfo.EndBallInfo(builder);
  }

  public static void StartBallInfo(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddPhysics(FlatBufferBuilder builder, Offset<Physics> physicsOffset) { builder.AddOffset(0, physicsOffset.Value, 0); }
  public static void AddLatestTouch(FlatBufferBuilder builder, Offset<Touch> latestTouchOffset) { builder.AddOffset(1, latestTouchOffset.Value, 0); }
  public static Offset<BallInfo> EndBallInfo(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<BallInfo>(o);
  }
};


}
