// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace rlbot.flat
{

using global::System;
using global::FlatBuffers;

public struct DesiredBallState : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static DesiredBallState GetRootAsDesiredBallState(ByteBuffer _bb) { return GetRootAsDesiredBallState(_bb, new DesiredBallState()); }
  public static DesiredBallState GetRootAsDesiredBallState(ByteBuffer _bb, DesiredBallState obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public DesiredBallState __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public DesiredPhysics? Physics { get { int o = __p.__offset(4); return o != 0 ? (DesiredPhysics?)(new DesiredPhysics()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<DesiredBallState> CreateDesiredBallState(FlatBufferBuilder builder,
      Offset<DesiredPhysics> physicsOffset = default(Offset<DesiredPhysics>)) {
    builder.StartObject(1);
    DesiredBallState.AddPhysics(builder, physicsOffset);
    return DesiredBallState.EndDesiredBallState(builder);
  }

  public static void StartDesiredBallState(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddPhysics(FlatBufferBuilder builder, Offset<DesiredPhysics> physicsOffset) { builder.AddOffset(0, physicsOffset.Value, 0); }
  public static Offset<DesiredBallState> EndDesiredBallState(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<DesiredBallState>(o);
  }
};


}
