// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace rlbot.flat
{

using global::System;
using global::FlatBuffers;

public struct DesiredCarState : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static DesiredCarState GetRootAsDesiredCarState(ByteBuffer _bb) { return GetRootAsDesiredCarState(_bb, new DesiredCarState()); }
  public static DesiredCarState GetRootAsDesiredCarState(ByteBuffer _bb, DesiredCarState obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public DesiredCarState __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public DesiredPhysics? Physics { get { int o = __p.__offset(4); return o != 0 ? (DesiredPhysics?)(new DesiredPhysics()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<DesiredCarState> CreateDesiredCarState(FlatBufferBuilder builder,
      Offset<DesiredPhysics> physicsOffset = default(Offset<DesiredPhysics>)) {
    builder.StartObject(1);
    DesiredCarState.AddPhysics(builder, physicsOffset);
    return DesiredCarState.EndDesiredCarState(builder);
  }

  public static void StartDesiredCarState(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddPhysics(FlatBufferBuilder builder, Offset<DesiredPhysics> physicsOffset) { builder.AddOffset(0, physicsOffset.Value, 0); }
  public static Offset<DesiredCarState> EndDesiredCarState(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<DesiredCarState>(o);
  }
};


}
