// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace rlbot.flat
{

using global::System;
using global::FlatBuffers;

public struct Float : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Float __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float Val { get { return __p.bb.GetFloat(__p.bb_pos + 0); } }

  public static Offset<Float> CreateFloat(FlatBufferBuilder builder, float Val) {
    builder.Prep(4, 4);
    builder.PutFloat(Val);
    return new Offset<Float>(builder.Offset);
  }
};


}
