// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace rlbot.flat
{

using global::System;
using global::FlatBuffers;

public struct GoalInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static GoalInfo GetRootAsGoalInfo(ByteBuffer _bb) { return GetRootAsGoalInfo(_bb, new GoalInfo()); }
  public static GoalInfo GetRootAsGoalInfo(ByteBuffer _bb, GoalInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public GoalInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int TeamNum { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public Vector3? Location { get { int o = __p.__offset(6); return o != 0 ? (Vector3?)(new Vector3()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public Vector3? Direction { get { int o = __p.__offset(8); return o != 0 ? (Vector3?)(new Vector3()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static void StartGoalInfo(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddTeamNum(FlatBufferBuilder builder, int teamNum) { builder.AddInt(0, teamNum, 0); }
  public static void AddLocation(FlatBufferBuilder builder, Offset<Vector3> locationOffset) { builder.AddStruct(1, locationOffset.Value, 0); }
  public static void AddDirection(FlatBufferBuilder builder, Offset<Vector3> directionOffset) { builder.AddStruct(2, directionOffset.Value, 0); }
  public static Offset<GoalInfo> EndGoalInfo(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GoalInfo>(o);
  }
};


}
