# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'car_customisation.ui'
#
# Created by: PyQt5 UI code generator 5.11
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LoadoutPresetCustomiser(object):
    def setupUi(self, LoadoutPresetCustomiser):
        LoadoutPresetCustomiser.setObjectName("LoadoutPresetCustomiser")
        LoadoutPresetCustomiser.resize(725, 510)
        self.centralwidget = QtWidgets.QWidget(LoadoutPresetCustomiser)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.presets_listwidget = QtWidgets.QListWidget(self.groupBox_3)
        self.presets_listwidget.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.presets_listwidget.setObjectName("presets_listwidget")
        self.verticalLayout.addWidget(self.presets_listwidget)
        self.frame = QtWidgets.QFrame(self.groupBox_3)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.preset_new_pushbutton = QtWidgets.QPushButton(self.frame)
        self.preset_new_pushbutton.setObjectName("preset_new_pushbutton")
        self.horizontalLayout_2.addWidget(self.preset_new_pushbutton)
        self.preset_load_pushbutton = QtWidgets.QPushButton(self.frame)
        self.preset_load_pushbutton.setObjectName("preset_load_pushbutton")
        self.horizontalLayout_2.addWidget(self.preset_load_pushbutton)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.right_frame = QtWidgets.QFrame(self.centralwidget)
        self.right_frame.setObjectName("right_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.right_frame)
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.preset_config_groupbox = QtWidgets.QGroupBox(self.right_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preset_config_groupbox.sizePolicy().hasHeightForWidth())
        self.preset_config_groupbox.setSizePolicy(sizePolicy)
        self.preset_config_groupbox.setObjectName("preset_config_groupbox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.preset_config_groupbox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_17 = QtWidgets.QLabel(self.preset_config_groupbox)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 2, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.preset_config_groupbox)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 0, 0, 1, 1)
        self.preset_autosave_checkbox = QtWidgets.QCheckBox(self.preset_config_groupbox)
        self.preset_autosave_checkbox.setObjectName("preset_autosave_checkbox")
        self.gridLayout_2.addWidget(self.preset_autosave_checkbox, 2, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.preset_path_lineedit = QtWidgets.QLineEdit(self.preset_config_groupbox)
        self.preset_path_lineedit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.preset_path_lineedit.setReadOnly(True)
        self.preset_path_lineedit.setObjectName("preset_path_lineedit")
        self.gridLayout_2.addWidget(self.preset_path_lineedit, 2, 1, 1, 1)
        self.preset_save_pushbutton = QtWidgets.QPushButton(self.preset_config_groupbox)
        self.preset_save_pushbutton.setObjectName("preset_save_pushbutton")
        self.gridLayout_2.addWidget(self.preset_save_pushbutton, 2, 2, 1, 1)
        self.preset_name_lineedit = QtWidgets.QLineEdit(self.preset_config_groupbox)
        self.preset_name_lineedit.setObjectName("preset_name_lineedit")
        self.gridLayout_2.addWidget(self.preset_name_lineedit, 0, 1, 1, 3)
        self.verticalLayout_4.addWidget(self.preset_config_groupbox)
        self.loadout_config_groupbox = QtWidgets.QGroupBox(self.right_frame)
        self.loadout_config_groupbox.setObjectName("loadout_config_groupbox")
        self.gridLayout = QtWidgets.QGridLayout(self.loadout_config_groupbox)
        self.gridLayout.setContentsMargins(-1, 0, -1, 8)
        self.gridLayout.setObjectName("gridLayout")
        self.label_14 = QtWidgets.QLabel(self.loadout_config_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 2, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.loadout_config_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 0, 5, 1, 2)
        self.label = QtWidgets.QLabel(self.loadout_config_groupbox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.blue_primary_spinbox = QtWidgets.QSpinBox(self.loadout_config_groupbox)
        self.blue_primary_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.blue_primary_spinbox.setMaximum(999999999)
        self.blue_primary_spinbox.setObjectName("blue_primary_spinbox")
        self.gridLayout.addWidget(self.blue_primary_spinbox, 1, 2, 1, 2)
        self.orange_primary_spinbox = QtWidgets.QSpinBox(self.loadout_config_groupbox)
        self.orange_primary_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.orange_primary_spinbox.setMaximum(999999999)
        self.orange_primary_spinbox.setObjectName("orange_primary_spinbox")
        self.gridLayout.addWidget(self.orange_primary_spinbox, 1, 5, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.loadout_config_groupbox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.loadout_config_groupbox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.orange_secondary_spinbox = QtWidgets.QSpinBox(self.loadout_config_groupbox)
        self.orange_secondary_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.orange_secondary_spinbox.setMaximum(999999999)
        self.orange_secondary_spinbox.setObjectName("orange_secondary_spinbox")
        self.gridLayout.addWidget(self.orange_secondary_spinbox, 2, 5, 1, 2)
        self.blue_secondary_spinbox = QtWidgets.QSpinBox(self.loadout_config_groupbox)
        self.blue_secondary_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.blue_secondary_spinbox.setMaximum(999999999)
        self.blue_secondary_spinbox.setObjectName("blue_secondary_spinbox")
        self.gridLayout.addWidget(self.blue_secondary_spinbox, 2, 2, 1, 2)
        self.blue_car_spinbox = QtWidgets.QSpinBox(self.loadout_config_groupbox)
        self.blue_car_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.blue_car_spinbox.setMaximum(999999)
        self.blue_car_spinbox.setObjectName("blue_car_spinbox")
        self.gridLayout.addWidget(self.blue_car_spinbox, 3, 2, 1, 1)
        self.orange_car_spinbox = QtWidgets.QSpinBox(self.loadout_config_groupbox)
        self.orange_car_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.orange_car_spinbox.setMaximum(999999)
        self.orange_car_spinbox.setObjectName("orange_car_spinbox")
        self.gridLayout.addWidget(self.orange_car_spinbox, 3, 5, 1, 1)
        self.orange_car_combobox = QtWidgets.QComboBox(self.loadout_config_groupbox)
        self.orange_car_combobox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.orange_car_combobox.setMinimumContentsLength(15)
        self.orange_car_combobox.setObjectName("orange_car_combobox")
        self.gridLayout.addWidget(self.orange_car_combobox, 3, 6, 1, 1)
        self.blue_car_combobox = QtWidgets.QComboBox(self.loadout_config_groupbox)
        self.blue_car_combobox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.blue_car_combobox.setMinimumContentsLength(15)
        self.blue_car_combobox.setObjectName("blue_car_combobox")
        self.gridLayout.addWidget(self.blue_car_combobox, 3, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.loadout_config_groupbox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.blue_decal_spinbox = QtWidgets.QSpinBox(self.loadout_config_groupbox)
        self.blue_decal_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.blue_decal_spinbox.setMaximum(999999)
        self.blue_decal_spinbox.setObjectName("blue_decal_spinbox")
        self.gridLayout.addWidget(self.blue_decal_spinbox, 4, 2, 1, 1)
        self.blue_decal_combobox = QtWidgets.QComboBox(self.loadout_config_groupbox)
        self.blue_decal_combobox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.blue_decal_combobox.setMinimumContentsLength(15)
        self.blue_decal_combobox.setObjectName("blue_decal_combobox")
        self.gridLayout.addWidget(self.blue_decal_combobox, 4, 3, 1, 1)
        self.orange_decal_spinbox = QtWidgets.QSpinBox(self.loadout_config_groupbox)
        self.orange_decal_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.orange_decal_spinbox.setMaximum(999999)
        self.orange_decal_spinbox.setObjectName("orange_decal_spinbox")
        self.gridLayout.addWidget(self.orange_decal_spinbox, 4, 5, 1, 1)
        self.blue_wheels_spinbox = QtWidgets.QSpinBox(self.loadout_config_groupbox)
        self.blue_wheels_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.blue_wheels_spinbox.setMaximum(999999)
        self.blue_wheels_spinbox.setObjectName("blue_wheels_spinbox")
        self.gridLayout.addWidget(self.blue_wheels_spinbox, 5, 2, 1, 1)
        self.blue_wheels_combobox = QtWidgets.QComboBox(self.loadout_config_groupbox)
        self.blue_wheels_combobox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.blue_wheels_combobox.setMinimumContentsLength(15)
        self.blue_wheels_combobox.setObjectName("blue_wheels_combobox")
        self.gridLayout.addWidget(self.blue_wheels_combobox, 5, 3, 1, 1)
        self.orange_wheels_spinbox = QtWidgets.QSpinBox(self.loadout_config_groupbox)
        self.orange_wheels_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.orange_wheels_spinbox.setMaximum(999999)
        self.orange_wheels_spinbox.setObjectName("orange_wheels_spinbox")
        self.gridLayout.addWidget(self.orange_wheels_spinbox, 5, 5, 1, 1)
        self.orange_decal_combobox = QtWidgets.QComboBox(self.loadout_config_groupbox)
        self.orange_decal_combobox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.orange_decal_combobox.setMinimumContentsLength(15)
        self.orange_decal_combobox.setObjectName("orange_decal_combobox")
        self.gridLayout.addWidget(self.orange_decal_combobox, 4, 6, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.loadout_config_groupbox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.orange_boost_spinbox = QtWidgets.QSpinBox(self.loadout_config_groupbox)
        self.orange_boost_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.orange_boost_spinbox.setMaximum(999999)
        self.orange_boost_spinbox.setObjectName("orange_boost_spinbox")
        self.gridLayout.addWidget(self.orange_boost_spinbox, 6, 5, 1, 1)
        self.blue_boost_combobox = QtWidgets.QComboBox(self.loadout_config_groupbox)
        self.blue_boost_combobox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.blue_boost_combobox.setMinimumContentsLength(15)
        self.blue_boost_combobox.setObjectName("blue_boost_combobox")
        self.gridLayout.addWidget(self.blue_boost_combobox, 6, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.loadout_config_groupbox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.orange_wheels_combobox = QtWidgets.QComboBox(self.loadout_config_groupbox)
        self.orange_wheels_combobox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.orange_wheels_combobox.setMinimumContentsLength(15)
        self.orange_wheels_combobox.setObjectName("orange_wheels_combobox")
        self.gridLayout.addWidget(self.orange_wheels_combobox, 5, 6, 1, 1)
        self.blue_boost_spinbox = QtWidgets.QSpinBox(self.loadout_config_groupbox)
        self.blue_boost_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.blue_boost_spinbox.setMaximum(999999)
        self.blue_boost_spinbox.setObjectName("blue_boost_spinbox")
        self.gridLayout.addWidget(self.blue_boost_spinbox, 6, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.loadout_config_groupbox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.blue_antenna_combobox = QtWidgets.QComboBox(self.loadout_config_groupbox)
        self.blue_antenna_combobox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.blue_antenna_combobox.setMinimumContentsLength(15)
        self.blue_antenna_combobox.setObjectName("blue_antenna_combobox")
        self.gridLayout.addWidget(self.blue_antenna_combobox, 7, 3, 1, 1)
        self.blue_antenna_spinbox = QtWidgets.QSpinBox(self.loadout_config_groupbox)
        self.blue_antenna_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.blue_antenna_spinbox.setMaximum(999999)
        self.blue_antenna_spinbox.setObjectName("blue_antenna_spinbox")
        self.gridLayout.addWidget(self.blue_antenna_spinbox, 7, 2, 1, 1)
        self.orange_antenna_spinbox = QtWidgets.QSpinBox(self.loadout_config_groupbox)
        self.orange_antenna_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.orange_antenna_spinbox.setMaximum(999999)
        self.orange_antenna_spinbox.setObjectName("orange_antenna_spinbox")
        self.gridLayout.addWidget(self.orange_antenna_spinbox, 7, 5, 1, 1)
        self.orange_boost_combobox = QtWidgets.QComboBox(self.loadout_config_groupbox)
        self.orange_boost_combobox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.orange_boost_combobox.setMinimumContentsLength(15)
        self.orange_boost_combobox.setObjectName("orange_boost_combobox")
        self.gridLayout.addWidget(self.orange_boost_combobox, 6, 6, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.loadout_config_groupbox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 8, 0, 1, 1)
        self.blue_hat_spinbox = QtWidgets.QSpinBox(self.loadout_config_groupbox)
        self.blue_hat_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.blue_hat_spinbox.setMaximum(999999)
        self.blue_hat_spinbox.setObjectName("blue_hat_spinbox")
        self.gridLayout.addWidget(self.blue_hat_spinbox, 8, 2, 1, 1)
        self.blue_hat_combobox = QtWidgets.QComboBox(self.loadout_config_groupbox)
        self.blue_hat_combobox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.blue_hat_combobox.setMinimumContentsLength(15)
        self.blue_hat_combobox.setObjectName("blue_hat_combobox")
        self.gridLayout.addWidget(self.blue_hat_combobox, 8, 3, 1, 1)
        self.orange_hat_spinbox = QtWidgets.QSpinBox(self.loadout_config_groupbox)
        self.orange_hat_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.orange_hat_spinbox.setMaximum(999999)
        self.orange_hat_spinbox.setObjectName("orange_hat_spinbox")
        self.gridLayout.addWidget(self.orange_hat_spinbox, 8, 5, 1, 1)
        self.orange_antenna_combobox = QtWidgets.QComboBox(self.loadout_config_groupbox)
        self.orange_antenna_combobox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.orange_antenna_combobox.setMinimumContentsLength(15)
        self.orange_antenna_combobox.setObjectName("orange_antenna_combobox")
        self.gridLayout.addWidget(self.orange_antenna_combobox, 7, 6, 1, 1)
        self.orange_hat_combobox = QtWidgets.QComboBox(self.loadout_config_groupbox)
        self.orange_hat_combobox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.orange_hat_combobox.setMinimumContentsLength(15)
        self.orange_hat_combobox.setObjectName("orange_hat_combobox")
        self.gridLayout.addWidget(self.orange_hat_combobox, 8, 6, 1, 1)
        self.blue_paint_finish_spinbox = QtWidgets.QSpinBox(self.loadout_config_groupbox)
        self.blue_paint_finish_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.blue_paint_finish_spinbox.setMaximum(999999)
        self.blue_paint_finish_spinbox.setObjectName("blue_paint_finish_spinbox")
        self.gridLayout.addWidget(self.blue_paint_finish_spinbox, 9, 2, 1, 1)
        self.blue_paint_finish_combobox = QtWidgets.QComboBox(self.loadout_config_groupbox)
        self.blue_paint_finish_combobox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.blue_paint_finish_combobox.setMinimumContentsLength(15)
        self.blue_paint_finish_combobox.setObjectName("blue_paint_finish_combobox")
        self.gridLayout.addWidget(self.blue_paint_finish_combobox, 9, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.loadout_config_groupbox)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 9, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.loadout_config_groupbox)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 10, 0, 1, 1)
        self.blue_custom_finish_combobox = QtWidgets.QComboBox(self.loadout_config_groupbox)
        self.blue_custom_finish_combobox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.blue_custom_finish_combobox.setMinimumContentsLength(15)
        self.blue_custom_finish_combobox.setObjectName("blue_custom_finish_combobox")
        self.gridLayout.addWidget(self.blue_custom_finish_combobox, 10, 3, 1, 1)
        self.orange_paint_finish_combobox = QtWidgets.QComboBox(self.loadout_config_groupbox)
        self.orange_paint_finish_combobox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.orange_paint_finish_combobox.setMinimumContentsLength(15)
        self.orange_paint_finish_combobox.setObjectName("orange_paint_finish_combobox")
        self.gridLayout.addWidget(self.orange_paint_finish_combobox, 9, 6, 1, 1)
        self.blue_custom_finish_spinbox = QtWidgets.QSpinBox(self.loadout_config_groupbox)
        self.blue_custom_finish_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.blue_custom_finish_spinbox.setMaximum(999999)
        self.blue_custom_finish_spinbox.setObjectName("blue_custom_finish_spinbox")
        self.gridLayout.addWidget(self.blue_custom_finish_spinbox, 10, 2, 1, 1)
        self.orange_paint_finish_spinbox = QtWidgets.QSpinBox(self.loadout_config_groupbox)
        self.orange_paint_finish_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.orange_paint_finish_spinbox.setMaximum(999999)
        self.orange_paint_finish_spinbox.setObjectName("orange_paint_finish_spinbox")
        self.gridLayout.addWidget(self.orange_paint_finish_spinbox, 9, 5, 1, 1)
        self.blue_engine_spinbox = QtWidgets.QSpinBox(self.loadout_config_groupbox)
        self.blue_engine_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.blue_engine_spinbox.setMaximum(999999)
        self.blue_engine_spinbox.setObjectName("blue_engine_spinbox")
        self.gridLayout.addWidget(self.blue_engine_spinbox, 11, 2, 1, 1)
        self.blue_engine_combobox = QtWidgets.QComboBox(self.loadout_config_groupbox)
        self.blue_engine_combobox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.blue_engine_combobox.setMinimumContentsLength(15)
        self.blue_engine_combobox.setObjectName("blue_engine_combobox")
        self.gridLayout.addWidget(self.blue_engine_combobox, 11, 3, 1, 1)
        self.orange_engine_spinbox = QtWidgets.QSpinBox(self.loadout_config_groupbox)
        self.orange_engine_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.orange_engine_spinbox.setMaximum(999999)
        self.orange_engine_spinbox.setObjectName("orange_engine_spinbox")
        self.gridLayout.addWidget(self.orange_engine_spinbox, 11, 5, 1, 1)
        self.orange_custom_finish_spinbox = QtWidgets.QSpinBox(self.loadout_config_groupbox)
        self.orange_custom_finish_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.orange_custom_finish_spinbox.setMaximum(999999)
        self.orange_custom_finish_spinbox.setObjectName("orange_custom_finish_spinbox")
        self.gridLayout.addWidget(self.orange_custom_finish_spinbox, 10, 5, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.loadout_config_groupbox)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 11, 0, 1, 1)
        self.orange_custom_finish_combobox = QtWidgets.QComboBox(self.loadout_config_groupbox)
        self.orange_custom_finish_combobox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.orange_custom_finish_combobox.setMinimumContentsLength(15)
        self.orange_custom_finish_combobox.setObjectName("orange_custom_finish_combobox")
        self.gridLayout.addWidget(self.orange_custom_finish_combobox, 10, 6, 1, 1)
        self.orange_engine_combobox = QtWidgets.QComboBox(self.loadout_config_groupbox)
        self.orange_engine_combobox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.orange_engine_combobox.setMinimumContentsLength(15)
        self.orange_engine_combobox.setObjectName("orange_engine_combobox")
        self.gridLayout.addWidget(self.orange_engine_combobox, 11, 6, 1, 1)
        self.blue_trails_combobox = QtWidgets.QComboBox(self.loadout_config_groupbox)
        self.blue_trails_combobox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.blue_trails_combobox.setMinimumContentsLength(15)
        self.blue_trails_combobox.setObjectName("blue_trails_combobox")
        self.gridLayout.addWidget(self.blue_trails_combobox, 12, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.loadout_config_groupbox)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 12, 0, 1, 1)
        self.blue_trails_spinbox = QtWidgets.QSpinBox(self.loadout_config_groupbox)
        self.blue_trails_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.blue_trails_spinbox.setMaximum(999999)
        self.blue_trails_spinbox.setObjectName("blue_trails_spinbox")
        self.gridLayout.addWidget(self.blue_trails_spinbox, 12, 2, 1, 1)
        self.orange_trails_spinbox = QtWidgets.QSpinBox(self.loadout_config_groupbox)
        self.orange_trails_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.orange_trails_spinbox.setMaximum(999999)
        self.orange_trails_spinbox.setObjectName("orange_trails_spinbox")
        self.gridLayout.addWidget(self.orange_trails_spinbox, 12, 5, 1, 1)
        self.orange_trails_combobox = QtWidgets.QComboBox(self.loadout_config_groupbox)
        self.orange_trails_combobox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.orange_trails_combobox.setMinimumContentsLength(15)
        self.orange_trails_combobox.setObjectName("orange_trails_combobox")
        self.gridLayout.addWidget(self.orange_trails_combobox, 12, 6, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.loadout_config_groupbox)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 13, 0, 1, 1)
        self.blue_goal_explosion_spinbox = QtWidgets.QSpinBox(self.loadout_config_groupbox)
        self.blue_goal_explosion_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.blue_goal_explosion_spinbox.setMaximum(999999)
        self.blue_goal_explosion_spinbox.setObjectName("blue_goal_explosion_spinbox")
        self.gridLayout.addWidget(self.blue_goal_explosion_spinbox, 13, 2, 1, 1)
        self.blue_goal_explosion_combobox = QtWidgets.QComboBox(self.loadout_config_groupbox)
        self.blue_goal_explosion_combobox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.blue_goal_explosion_combobox.setMinimumContentsLength(15)
        self.blue_goal_explosion_combobox.setObjectName("blue_goal_explosion_combobox")
        self.gridLayout.addWidget(self.blue_goal_explosion_combobox, 13, 3, 1, 1)
        self.orange_goal_explosion_combobox = QtWidgets.QComboBox(self.loadout_config_groupbox)
        self.orange_goal_explosion_combobox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.orange_goal_explosion_combobox.setMinimumContentsLength(15)
        self.orange_goal_explosion_combobox.setObjectName("orange_goal_explosion_combobox")
        self.gridLayout.addWidget(self.orange_goal_explosion_combobox, 13, 6, 1, 1)
        self.orange_goal_explosion_spinbox = QtWidgets.QSpinBox(self.loadout_config_groupbox)
        self.orange_goal_explosion_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.orange_goal_explosion_spinbox.setMaximum(999999)
        self.orange_goal_explosion_spinbox.setObjectName("orange_goal_explosion_spinbox")
        self.gridLayout.addWidget(self.orange_goal_explosion_spinbox, 13, 5, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.loadout_config_groupbox)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 1, 13, 1)
        self.line = QtWidgets.QFrame(self.loadout_config_groupbox)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 4, 13, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setColumnStretch(3, 2)
        self.gridLayout.setColumnStretch(4, 1)
        self.gridLayout.setColumnStretch(5, 1)
        self.gridLayout.setColumnStretch(6, 2)
        self.verticalLayout_4.addWidget(self.loadout_config_groupbox)
        self.verticalLayout_4.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.right_frame)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 5)
        LoadoutPresetCustomiser.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(LoadoutPresetCustomiser)
        self.statusbar.setObjectName("statusbar")
        LoadoutPresetCustomiser.setStatusBar(self.statusbar)

        self.retranslateUi(LoadoutPresetCustomiser)
        QtCore.QMetaObject.connectSlotsByName(LoadoutPresetCustomiser)

    def retranslateUi(self, LoadoutPresetCustomiser):
        _translate = QtCore.QCoreApplication.translate
        LoadoutPresetCustomiser.setWindowTitle(_translate("LoadoutPresetCustomiser", "Loadout Preset Customiser"))
        self.groupBox_3.setTitle(_translate("LoadoutPresetCustomiser", "Loadout Presets"))
        self.presets_listwidget.setSortingEnabled(True)
        self.preset_new_pushbutton.setText(_translate("LoadoutPresetCustomiser", "New"))
        self.preset_load_pushbutton.setText(_translate("LoadoutPresetCustomiser", "Load"))
        self.preset_config_groupbox.setTitle(_translate("LoadoutPresetCustomiser", "Preset Config"))
        self.label_17.setText(_translate("LoadoutPresetCustomiser", "File Path:"))
        self.label_16.setText(_translate("LoadoutPresetCustomiser", "Preset Name:"))
        self.preset_autosave_checkbox.setText(_translate("LoadoutPresetCustomiser", "Autosave"))
        self.preset_path_lineedit.setPlaceholderText(_translate("LoadoutPresetCustomiser", "Currently not stored on disk"))
        self.preset_save_pushbutton.setText(_translate("LoadoutPresetCustomiser", "Save"))
        self.loadout_config_groupbox.setTitle(_translate("LoadoutPresetCustomiser", "Loadout"))
        self.label_14.setText(_translate("LoadoutPresetCustomiser", "Blue"))
        self.label_15.setText(_translate("LoadoutPresetCustomiser", "Orange"))
        self.label.setText(_translate("LoadoutPresetCustomiser", "Primary Colour:"))
        self.label_2.setText(_translate("LoadoutPresetCustomiser", "Secondary Colour:"))
        self.label_3.setText(_translate("LoadoutPresetCustomiser", "Car:"))
        self.label_4.setText(_translate("LoadoutPresetCustomiser", "Decal:"))
        self.label_5.setText(_translate("LoadoutPresetCustomiser", "Wheels:"))
        self.label_6.setText(_translate("LoadoutPresetCustomiser", "Boost:"))
        self.label_7.setText(_translate("LoadoutPresetCustomiser", "Antenna:"))
        self.label_8.setText(_translate("LoadoutPresetCustomiser", "Hat:"))
        self.label_9.setText(_translate("LoadoutPresetCustomiser", "Paint Finish:"))
        self.label_10.setText(_translate("LoadoutPresetCustomiser", "Custom Finish:"))
        self.label_11.setText(_translate("LoadoutPresetCustomiser", "Engine Audio:"))
        self.label_12.setText(_translate("LoadoutPresetCustomiser", "Trail:"))
        self.label_13.setText(_translate("LoadoutPresetCustomiser", "Goal Explosion:"))

