# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mutator_customisation.ui'
#
# Created by: PyQt5 UI code generator 5.11
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MutatorCustomiser(object):
    def setupUi(self, MutatorCustomiser):
        MutatorCustomiser.setObjectName("MutatorCustomiser")
        MutatorCustomiser.resize(327, 269)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MutatorCustomiser.sizePolicy().hasHeightForWidth())
        MutatorCustomiser.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MutatorCustomiser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.overtime_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.overtime_combobox.setObjectName("overtime_combobox")
        self.gridLayout.addWidget(self.overtime_combobox, 2, 1, 1, 1)
        self.boost_amount_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.boost_amount_combobox.setObjectName("boost_amount_combobox")
        self.gridLayout.addWidget(self.boost_amount_combobox, 2, 4, 1, 1)
        self.gravity_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.gravity_combobox.setObjectName("gravity_combobox")
        self.gridLayout.addWidget(self.gravity_combobox, 5, 4, 1, 1)
        self.boost_strength_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.boost_strength_combobox.setObjectName("boost_strength_combobox")
        self.gridLayout.addWidget(self.boost_strength_combobox, 4, 4, 1, 1)
        self.rumble_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.rumble_combobox.setObjectName("rumble_combobox")
        self.gridLayout.addWidget(self.rumble_combobox, 3, 4, 1, 1)
        self.demolish_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.demolish_combobox.setObjectName("demolish_combobox")
        self.gridLayout.addWidget(self.demolish_combobox, 6, 4, 1, 1)
        self.respawn_time_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.respawn_time_combobox.setObjectName("respawn_time_combobox")
        self.gridLayout.addWidget(self.respawn_time_combobox, 7, 4, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 2, 8, 1)
        self.ball_max_speed_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.ball_max_speed_combobox.setObjectName("ball_max_speed_combobox")
        self.gridLayout.addWidget(self.ball_max_speed_combobox, 5, 1, 1, 1)
        self.series_length_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.series_length_combobox.setObjectName("series_length_combobox")
        self.gridLayout.addWidget(self.series_length_combobox, 3, 1, 1, 1)
        self.ball_type_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.ball_type_combobox.setObjectName("ball_type_combobox")
        self.gridLayout.addWidget(self.ball_type_combobox, 6, 1, 1, 1)
        self.ball_weight_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.ball_weight_combobox.setObjectName("ball_weight_combobox")
        self.gridLayout.addWidget(self.ball_weight_combobox, 7, 1, 1, 1)
        self.game_speed_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.game_speed_combobox.setObjectName("game_speed_combobox")
        self.gridLayout.addWidget(self.game_speed_combobox, 4, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 5, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.match_length_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.match_length_combobox.setObjectName("match_length_combobox")
        self.gridLayout.addWidget(self.match_length_combobox, 0, 1, 1, 1)
        self.max_score_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.max_score_combobox.setObjectName("max_score_combobox")
        self.gridLayout.addWidget(self.max_score_combobox, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.ball_size_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.ball_size_combobox.setObjectName("ball_size_combobox")
        self.gridLayout.addWidget(self.ball_size_combobox, 0, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 7, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 6, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 3, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 4, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 7, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 6, 3, 1, 1)
        self.ball_bounciness_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.ball_bounciness_combobox.setObjectName("ball_bounciness_combobox")
        self.gridLayout.addWidget(self.ball_bounciness_combobox, 1, 4, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, 4, 5, -1)
        self.horizontalLayout.setSpacing(11)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.reset_default_pushbutton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_default_pushbutton.sizePolicy().hasHeightForWidth())
        self.reset_default_pushbutton.setSizePolicy(sizePolicy)
        self.reset_default_pushbutton.setObjectName("reset_default_pushbutton")
        self.horizontalLayout.addWidget(self.reset_default_pushbutton)
        self.close_pushbutton = QtWidgets.QPushButton(self.centralwidget)
        self.close_pushbutton.setObjectName("close_pushbutton")
        self.horizontalLayout.addWidget(self.close_pushbutton)
        self.gridLayout.addLayout(self.horizontalLayout, 10, 0, 1, 5)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 4)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setColumnStretch(3, 2)
        self.gridLayout.setColumnStretch(4, 4)
        MutatorCustomiser.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MutatorCustomiser)
        self.statusbar.setObjectName("statusbar")
        MutatorCustomiser.setStatusBar(self.statusbar)

        self.retranslateUi(MutatorCustomiser)
        QtCore.QMetaObject.connectSlotsByName(MutatorCustomiser)

    def retranslateUi(self, MutatorCustomiser):
        _translate = QtCore.QCoreApplication.translate
        MutatorCustomiser.setWindowTitle(_translate("MutatorCustomiser", "Mutator Configurator"))
        self.label_14.setText(_translate("MutatorCustomiser", "Gravity"))
        self.label_2.setText(_translate("MutatorCustomiser", "Ball Size"))
        self.label_3.setText(_translate("MutatorCustomiser", "Max Score"))
        self.label_5.setText(_translate("MutatorCustomiser", "Overtime"))
        self.label_4.setText(_translate("MutatorCustomiser", "Ball Bounciness"))
        self.label_7.setText(_translate("MutatorCustomiser", "Game Speed"))
        self.label_6.setText(_translate("MutatorCustomiser", "Series Length"))
        self.label_10.setText(_translate("MutatorCustomiser", "Ball Weight"))
        self.label_9.setText(_translate("MutatorCustomiser", "Ball Type"))
        self.label_8.setText(_translate("MutatorCustomiser", "Ball Max Speed"))
        self.label.setText(_translate("MutatorCustomiser", "MatchLength"))
        self.label_11.setText(_translate("MutatorCustomiser", "Boost Amount"))
        self.label_12.setText(_translate("MutatorCustomiser", "Rumble"))
        self.label_13.setText(_translate("MutatorCustomiser", "Boost Strength"))
        self.label_16.setText(_translate("MutatorCustomiser", "Respawn Time"))
        self.label_15.setText(_translate("MutatorCustomiser", "Demolish"))
        self.reset_default_pushbutton.setText(_translate("MutatorCustomiser", "Reset Default"))
        self.close_pushbutton.setText(_translate("MutatorCustomiser", "Close"))

